Deep links#46
IMGIITRoorkee/Taskly pull request #57
Opened 2024-12-16 17:35 UTC by sommye-ctr

### Related Issue  
Closes #46 

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature

### Description of Change  
This adds functionality to open links of our app, directly into it. The link should be of the format - `taskly://taskly.com`. Configuration for both android and iOS is done and functionality has been checked on both. 

NOTE - custom scheme (taskly) is used instead of http or https since handling them would need having our custom domain.

### Implementation Details  
Added intent filter in android's manifest and added custom url type in iOS info.plist along with adding domain in runner.

### Demo  

https://github.com/user-attachments/assets/23981fa6-3e9f-4049-886a-b0ccfdd176a4

2024-12-17 09:29 UTC, lakshita10341 commented
@sommye-ctr  first resolve merge conflicts

2024-12-17 09:54 UTC, sommye-ctr commented
@lakshita10341 resolved

2024-12-17 14:21 UTC, pranavkonidena requested changes
These look good so far? What about adding changes so that you directly open a task from it's link instead of only going to the home page?

2024-12-27 12:40 UTC, sommye-ctr commented
@pranavkonidena Changes are made as per requested. An `id` column is added to Task so that to identify tasks uniquely. So to work, we would need to clear all the prev tasks in storage (one would ideally migrate this change by comparing versions of the app in production). Also, no third party packages are used in this.

The url scheme for sharing would be `taskly:/taskly.com?id={id}`


https://github.com/user-attachments/assets/0c382e93-24ac-4026-80da-e1128ea7c1bf

2024-12-28 14:22 UTC, sommye-ctr commented
@pranavkonidena resolved conflicts

2025-01-04 10:13 UTC, sommye-ctr commented
@pranavkonidena kindly review this as it has been 3 weeks for the PR

2025-01-04 10:22 UTC, pranavkonidena commented
> @pranavkonidena kindly review this as it has been 3 weeks for the PR

Sure will review it today

2025-01-08 13:49 UTC, pranavkonidena approved these changes
These changes LGTM! On resolving merge conflicts, these will be merged @sommye-ctr

2025-01-08 17:15 UTC, merged