Task dependency feature added #28
IMGIITRoorkee/Taskly pull request #80
Opened 2024-12-20 17:33 UTC by Sanat-Jha

### Related Issue  
Closes #28  

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature 

### Description of Change  
Now one can add a dependency task to a new task so that the user first has to complete the dependent task to mark this task as complete.

2024-12-28 13:59 UTC, Sanat-Jha commented
@pranavkonidena  merge conflicts resolved. Please Review

2024-12-29 09:34 UTC, lakshita10341 commented
@Sanat-Jha  Your PR is missing the implementation for visually distinguishing tasks with dependencies. Consider adding indicators like arrows or similar visual cues to represent task dependencies clearly.

2024-12-29 12:16 UTC, Sanat-Jha commented
@lakshita10341 Indication added. Link icon in task list tile shows that it is a dependent task and its colour shows that the dependent task is pending or complete. The  task details box shows that on which task it is dependent and state of dependency.

2025-01-08 11:26 UTC, pranavkonidena requested changes
Just these minor changes remain, please get this done and this will be merged! Rest, LGTM

2025-01-08 11:26 UTC, pranavkonidena commented on lib/screens/home_screen.dart
> +        msg: 'Complete the dependency first!',
Please add this message in constants file

2025-01-08 11:26 UTC, pranavkonidena commented on lib/screens/taskform_screen.dart
> +}
Please add an empty End of File here

2025-01-08 11:38 UTC, Sanat-Jha commented
@pranavkonidena Added EOF and constant message and also removed the repeating code.

2025-01-08 11:43 UTC, pranavkonidena requested changes

2025-01-08 11:43 UTC, pranavkonidena commented on lib/constants.dart
>      "Session ended. You meditated for $minutesMeditated minutes and $secondsMeditated seconds";
Shouldn't this be defined as 
```AskDependencyCompletion = "Complete the dependency first!"? ```
Also, here EOF is not there.. please add end of file here as well

2025-01-08 11:52 UTC, Sanat-Jha commented on lib/constants.dart
>      "Session ended. You meditated for $minutesMeditated minutes and $secondsMeditated seconds";
Pardon my error, fixing this.

2025-01-08 11:53 UTC, Sanat-Jha commented on lib/constants.dart
>      "Session ended. You meditated for $minutesMeditated minutes and $secondsMeditated seconds";
@pranavkonidena Solved the error

2025-01-08 11:56 UTC, pranavkonidena approved these changes
LGTM! Ready for merge

2025-01-08 11:56 UTC, merged